name: Windows Dependencies

on:
  workflow_call:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

defaults:
  run:
    shell: pwsh

jobs:
  build_wx:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -URI https://github.com/wxWidgets/wxWidgets/releases/download/v3.2.2.1/wxWidgets-3.2.2.1.zip -OutFile sources.zip
      - run: Expand-Archive ./sources.zip
      - run: mkdir wx_build
      - run: mkdir cmake_build
      - run: cmake -B ../cmake_build -DCMAKE_INSTALL_PREFIX="../wx_build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=OFF
        working-directory: sources
      - run: cmake --build ../cmake_build --config ${{env.BUILD_TYPE}}
        working-directory: sources
      - run: cmake --install ../cmake_build
        working-directory: sources
      - name: 'Upload wxWidgets Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: wx_build
          path: wx_build/*
          retention-days: 1
  
  build_lua:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -URI https://www.lua.org/ftp/lua-5.4.4.tar.gz -OutFile lua-5.4.4.tar.gz
      - run: tar -xzf lua-5.4.4.tar.gz
      - working-directory: lua-5.4.4
        run: Invoke-WebRequest -URI https://raw.githubusercontent.com/KAHR-Alpha/Aether/main/contribs/lua_cmakelist/CMakeLists.txt -OutFile CMakeLists.txt
      - run: cmake -B "${{github.workspace}}/cmake_build" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/lua_build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        working-directory: lua-5.4.4
      - run: cmake --build "${{github.workspace}}/cmake_build" --config ${{env.BUILD_TYPE}}
        working-directory: lua-5.4.4
      - run: cmake --install "${{github.workspace}}/cmake_build"
        working-directory: lua-5.4.4
      - name: 'Upload Lua Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: lua_build
          path: lua_build/*
          retention-days: 1
            
  build_zlib:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -URI https://zlib.net/zlib1213.zip -OutFile sources.zip
      - run: Expand-Archive ./sources.zip
      - run: cmake -B "${{github.workspace}}/cmake_build" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/zlib_build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        working-directory: sources/zlib-1.2.13
      - run: cmake --build "${{github.workspace}}/cmake_build" --config ${{env.BUILD_TYPE}}
        working-directory: sources/zlib-1.2.13
      - run: cmake --install "${{github.workspace}}/cmake_build"
        working-directory: sources/zlib-1.2.13
      - name: 'Upload zlib Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: zlib_build
          path: zlib_build/*
          retention-days: 1
          
  build_libpng:
    runs-on: windows-latest
    needs: build_zlib
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: zlib_build
          path: zlib_build
      - run: Invoke-WebRequest -UserAgent "Wget" -URI https://sourceforge.net/projects/libpng/files/latest/download -OutFile sources.zip
      - run: Expand-Archive ./sources.zip
      #- run: mkdir cmake_build
      #- run: mkdir libpng_build
      - run: cmake -B "${{github.workspace}}/cmake_build" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/libpng_build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="../../zlib_build"
        working-directory: sources/lpng1639
      - run: cmake --build "${{github.workspace}}/cmake_build" --config ${{env.BUILD_TYPE}}
        working-directory: sources/lpng1639
      - run: cmake --install "${{github.workspace}}/cmake_build"
        working-directory: sources/lpng1639
      - name: 'Upload libpng Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: libpng_build
          path: libpng_build/*
          retention-days: 1
          
  build_freetype:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -UserAgent "Wget" -URI https://sourceforge.net/projects/freetype/files/latest/download -OutFile sources.zip
      - run: Expand-Archive ./sources.zip
      - run: cmake -B "${{github.workspace}}/cmake_build" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/freetype_build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        working-directory: sources/freetype-2.13.1
      - run: cmake --build "${{github.workspace}}/cmake_build" --config ${{env.BUILD_TYPE}}
        working-directory: sources/freetype-2.13.1
      - run: cmake --install "${{github.workspace}}/cmake_build"
        working-directory: sources/freetype-2.13.1
      - name: 'Upload libpng Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: freetype_build
          path: freetype_build/*
          retention-days: 1
          
  get_fftw:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - run: Invoke-WebRequest -URI https://fftw.org/pub/fftw/fftw-3.3.5-dll64.zip -OutFile fftw.zip
      - run: Expand-Archive ./fftw.zip
      - name: Generate FFTW Lib
        working-directory: fftw
        run: lib /def:libfftw3-3.def
      - name: 'Upload fftw Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: fftw
          path: fftw/*
          retention-days: 1

  build_eigen:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -URI https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip -OutFile eigen-3.4.0.zip
      - run: Expand-Archive ./eigen-3.4.0.zip
      - name: build
        run: cmake -B "${{github.workspace}}/build" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/Eigen_build" -DCMAKE_BUILD_TYPE=Release
        working-directory: eigen-3.4.0/eigen-3.4.0
      - run: cmake --build "${{github.workspace}}/build"
        working-directory: eigen-3.4.0/eigen-3.4.0
      - run: cmake --install "${{github.workspace}}/build"
        working-directory: eigen-3.4.0/eigen-3.4.0
      - name: 'Upload Eigen Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: eigen_build
          path: Eigen_build/*
          retention-days: 1
