name: Windows Build

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  collect_dependencies:
    uses: ./.github/workflows/windows_dependencies.yml
  
  build:
    needs: collect_dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        uses: actions/download-artifact@v3
      - run: Copy-Item -Force wx_build/lib/vc_x64_dll/mswu/* wx_build/include/
      - name: Configure CMake
        run: cmake -B "build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="" -DTASK="Build CLI+GUI" -DLUA_INCLUDE_DIR="lua_build/src" -DLUA_LIBRARIES="lua_build/src/liblua.a" -DEIGEN3_INCLUDE_DIR="eigen_build/include/eigen3" -DFREETYPE_INCLUDE_DIRS="freetype_build/include/freetype2" -DFREETYPE_LIBRARIES="freetype_build/lib/freetype.lib" -DWXWIDGETS_INCLUDES="wx_build/include" -DWXWIDGETS_ADV="wx_build/lib/vc_x64_dll/wxmsw32u_adv.lib" -DWXWIDGETS_BASE="wx_build/lib/vc_x64_dll/wxbase32u.lib" -DWXWIDGETS_CORE="wx_build/lib/vc_x64_dll/wxmsw32u_core.lib" -DWXWIDGETS_GL="wx_build/lib/vc_x64_dll/wxmsw32u_gl.lib"  -DFFTW_LIB="fftw/libfftw3-3.dll" -DCMAKE_PREFIX_PATH="fftw;zlib_build;libpng_build;freetype_build/lib/cmake/freetype"

      - name: Build
        # Build your program with the given configuration
        run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}

      #- name: Test
        #working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        #run: ctest -C ${{env.BUILD_TYPE}}
