name: Windows Libpng Caching
on:
  workflow_call:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

defaults:
  run:
    shell: pwsh

jobs:
  build_libpng:
    runs-on: windows-latest
    steps:
      - name: Enable Cache
        id: cache-action
        uses: actions/cache@v3
        with:
          path: builds/*
          key: ${{ runner.os }}-cache-key
          
      - name: Enable Cache
        uses: actions/cache@v3
        with:
          path: builds/libpng
          key: ${{ runner.os }}-cache-key-libpng
      
      - name: Check the cache
        if: steps.cache-action.outputs.cache-hit == 'true'
        run: dir builds
          
      - run: Invoke-WebRequest -UserAgent "Wget" -URI https://sourceforge.net/projects/libpng/files/latest/download -OutFile sources.zip
      - run: Expand-Archive ./sources.zip
      
      - run: cmake -B "${{github.workspace}}/cmake_build" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/builds/libpng" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="${{github.workspace}}/builds/zlib"
        working-directory: sources/lpng1639
        
      - run: cmake --build "${{github.workspace}}/cmake_build" --config ${{env.BUILD_TYPE}}
        working-directory: sources/lpng1639
        
      - run: cmake --install "${{github.workspace}}/cmake_build"
        working-directory: sources/lpng1639
