name: Windows Zlib Caching
on:
  workflow_call:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

defaults:
  run:
    shell: pwsh

jobs:
  build_zlib:
    runs-on: windows-latest
    steps:
      - name: Enable Cache
        id: cache-action
        uses: actions/cache@v3
        with:
          path: builds/*
          key: ${{ runner.os }}-cache-key
      
      - name: Use or generate the cache
        if: steps.cache-action.outputs.cache-hit == 'true'
        run: dir builds
        
      - run: Invoke-WebRequest -URI https://zlib.net/zlib1213.zip -OutFile sources.zip
      - run: Expand-Archive ./sources.zip
      
      - run: cmake -B "${{github.workspace}}/cmake_build" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/builds/zlib" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        working-directory: sources/zlib-1.2.13
        
      - run: cmake --build "${{github.workspace}}/cmake_build" --config ${{env.BUILD_TYPE}}
        working-directory: sources/zlib-1.2.13
        
      - run: cmake --install "${{github.workspace}}/cmake_build"
        working-directory: sources/zlib-1.2.13
        