name: Windows Build

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Collect_dependencies:
    uses: ./.github/workflows/windows_dependencies.yml
  
  Build_Aether:
    needs: Collect_dependencies
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        uses: actions/download-artifact@v3
      - run: Copy-Item -Force wx_build/lib/vc_x64_lib/mswu/wx/setup.h wx_build/include/wx
      - name: Configure CMake
        run: cmake -B "${{github.workspace}}/cmake_build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_PATH="Aether" -DTASK="Build CLI+GUI" -DLUA_INCLUDE_DIR="${{github.workspace}}/lua_build/include" -DLUA_LIBRARIES="${{github.workspace}}/lua_build/lib/lua.lib" -DEIGEN3_INCLUDE_DIR="${{github.workspace}}/eigen_build/include/eigen3" -DFREETYPE_INCLUDE_DIRS="${{github.workspace}}/freetype_build/include/freetype2" -DFREETYPE_LIBRARIES="${{github.workspace}}/freetype_build/lib/freetype.lib" -DFREETYPE_LIBRARY="${{github.workspace}}/freetype_build/lib/freetype.lib" -DWXWIDGETS_INCLUDES="${{github.workspace}}/wx_build/include" -DWXWIDGETS_ADV="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxmsw32u_adv.lib" -DWXWIDGETS_BASE="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxbase32u.lib" -DWXWIDGETS_CORE="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxmsw32u_core.lib" -DWXWIDGETS_GL="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxmsw32u_gl.lib" -DWXWIDGETS_PNG="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxpng.lib" -DWXWIDGETS_JPEG="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxjpeg.lib" -DWXWIDGETS_TIFF="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxtiff.lib" -DWXWIDGETS_ZLIB="${{github.workspace}}/wx_build/lib/vc_x64_lib/wxzlib.lib" -DFFTW_LIB="${{github.workspace}}/fftw/libfftw3-3.lib" -DCMAKE_PREFIX_PATH="fftw;zlib_build;libpng_build;freetype_build/lib/cmake/freetype;eigen_build/share/eigen3/cmake"

      - name: Build
        run: cmake --build "${{github.workspace}}/cmake_build" --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install "${{github.workspace}}/cmake_build"
        
      - name: 'Upload Aether Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Aether
          path: Aether/*
          retention-days: 1